### ISSUE TITLE
Brilliant Ansible Role

### ISSUE THREAD

**Issue by vialcollet** [solarkennedy/xkyle.com#2]
Hi and congratulations for your efforts and nice review. Thank you also for your training on Udemy. I'll be the intermediate one.
I read it after installing Sensu with Ansible though...
I found this module which might change your perception on installing Sensu with Ansible and even maybe on Ansible itself: https://github.com/cmacrae/ansible-sensu/
This role is brilliant because it perfectly integrates into your inventory management and allow the user to manage the monitoring with Ansible.
As with any Ansible role you can override your defaults (for example the defaults checks) based on groups of hosts and/or by host.
Let me know what you think!

**Comment by solarkennedy** [comment]
I agree this looks like a very comprehensive ansible role for sensu, however I'm still a believer in having separate roles for doing their own thing (one for rabbitmq, one for redis, etc) instead of having one role to handle all the logic and pieces like this one.

I do like the integration between the inventory and the dynamic checks. This is pretty fancy and I've never see this kind of integration in any other ansible playbooks.
